version: "3"
services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 4000:4000
    command: ./myApp
    environment:
      connection: postgres://postgres:duman070601@host.docker.internal:5432/snippetbox?sslmode=disable
    restart: always
    depends_on:
      - database

  database:
    image: postgres
    container_name: postgres_container
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: duman070601
      POSTGRES_DB: snippetbox
    restart: always

volumes:
  postgres-data: